### ISSUE TITLE
Await later calls

### ISSUE THREAD

**Issue by nx10** [r-lib/later#137]
I am trying to write a thread safe wrapper for later and am running into issues with exception handling.

My main goal is to "await" when later calls return.

The following code works well overall but the mutex wont get unlocked if an exception occurs in the later call. Then the mutex never gets unlocked despite the try/catch.

```c++
#include <mutex>
#include <later_api.h>

namespace asynclater {

        std::mutex later_mutex;

        struct AsyncLaterData
        {
            void (*func)(void *);
            void *data;
        } rsdat;

        void later(void (*func)(void *), void *data, double secs)
        {
            later_mutex.lock();
            rsdat.data = data;
            rsdat.func = func;
            later::later([](void *data) {
                try
                {
                    auto d = static_cast<AsyncLaterData *>(data);
                    d->func(d->data);
                }
                catch (...)
                {
                } // make sure mutex gets unlocked (does not work)
                later_mutex.unlock();
            },
                         &rsdat, secs);
        }

        void awaitLater()
        {
            later_mutex.lock();
            later_mutex.unlock();
        }

}
```

I am not sure if this is intentional. If it is do you have a suggestion how I can work around it?

**Comment by wch** [comment]
I haven't used lambdas in C++ before, but I think it may not be safe to pass one directly to `later()` like that. `later()` expects a bare function pointer; I don't know what kind of magic the compiler is doing to the lambda to provide the function pointer to `later()`.

Since `later()` takes a bare pointer, I don't think that the compiler is able to track the lifetime of the `std::function` from your lambda, and so I think the lambda will be destroyed before it is invoked.

It is possible to wrap up `function` objects so that `later()` can handle them, but it currently involves adding a bit of code similar to [this](https://github.com/rstudio/httpuv/blob/5bb43428816d175cf66d906599c7569519c67b27/src/callback.cpp). However, now that we're using C++11 in various packages, we could make `later()` take `std::function` objects directly so that extra code isn't necessary (but that won't help you currently).

After dealing with the lifetime issues, here are some ideas:
* Have you tried using RAII to unlock the mutex? I know you can't RAII to both lock and unlock the mutex, but you could use it just for unlocking.
* Does any code after the `catch` execute?

**Comment by nx10** [comment]
As far as I know lambdas can decay into function pointers as long as they don't capture anything.

here is some code for reproducing the problem:

```R
Rcpp::cppFunction('
#include <Rcpp.h>
#include "later_api.h"

int later_rferror()
{

    later::later([](void *data) {
        try
        {
            Rcpp::Rcout << "A\\n";
            Rf_error("some error\\n");
            Rcpp::Rcout << "B\\n";
        }
        catch (...)
        {
            Rcpp::Rcout << "C\\n";
        }
        Rcpp::Rcout << "D\\n";
    },
                 0, 0);
    return 1;
}', depends=c("later"))
```

Calling `later_rferror()` results in:

```
[1] 1
A
Error: some error
later: exception occurred while executing callback: 

```

Here the same function with `Rcpp::stop(...)`:

```R
Rcpp::cppFunction('
#include <Rcpp.h>
#include "later_api.h"

int later_rcppstop()
{

    later::later([](void *data) {
        try
        {
            Rcpp::Rcout << "A\\n";
            Rcpp::stop("some error\\n");
            Rcpp::Rcout << "B\\n";
        }
        catch (...)
        {
            Rcpp::Rcout << "C\\n";
        }
        Rcpp::Rcout << "D\\n";
    },
                 0, 0);
    return 1;
}', depends=c("later"))
```

Here the catching works and results in:

```
[1] 1
A
C
D
```

RAII also does not seem to work:

```R
Rcpp::cppFunction('
#include <Rcpp.h>
#include "later_api.h"

int later_rferror_raii()
{
    later::later([](void *data) {
    
        class raiitest
        {
        public:
          raiitest() { Rcpp::Rcout << "raii init\\n"; }
          ~raiitest() { Rcpp::Rcout << "raii destruct\\n"; }
        };

        raiitest myraii = raiitest();
        try
        {
            Rcpp::Rcout << "A\\n";
            Rf_error("some error\\n");
            Rcpp::Rcout << "B\\n";
        }
        catch (...)
        {
            Rcpp::Rcout << "C\\n";
        }
        Rcpp::Rcout << "D\\n";
    },
                 0, 0);
    return 1;
}', depends=c("later"))
```

Results in:

```
[1] 1
raii init
A
Error: some error
later: exception occurred while executing callback: 
```

**Comment by wch** [comment]
Oh, the issue is simple. `Rf_error()` is a C function for throwing an error at the R level (similar to calling `stop()` in R code). It's a C function and it doesn't throw a C++ exception. My rough understanding is that it's implemented with `longjmp`, and that does not play well with C++ exception handling and destructors. See here for more information about it:
  https://developer.r-project.org/Blog/public/2019/03/28/use-of-c---in-packages/index.html

I think the most straightforward way to deal with this is to wrap your code in a `tryCatch`, in R code.

This may help: I have an example [here](https://gist.github.com/wch/4c54c765d16fdd9328e763db22512c4f) for constructing an expression from C and `eval`-ing it. All you really need to do is create a wrapper closure in R which does the `tryCatch()` around the code you really want to run, and then invoke that.

**Comment by nx10** [comment]
Thank you for the information.

My application is performance sensitive so I am looking at [`R_UnwindProtect`](https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Condition-handling-and-cleanup-code) linked in the article you referenced for a solution with less overhead. (Even if I am not sure that I understand how to use it yet.)

As the issue is with the R C API I will close this issue. Thanks for all your help!
