### ISSUE TITLE
Rstudio server and the R event loop

### ISSUE THREAD

**Issue by hcorrada** [r-lib/later#2]
Hi @jcheng5,

Awesome work on this! Look forward to start using it. I'm putting this issue here since this might be the smallest replicable example of this behavior, but it affects httpuv daemonization as well. 

It seems that Rstudio server is messing with the R posix event loop (addInputHandler and friends). So the simple `later::later(~print("Hello"))` example doesn't work, as it doesn't evaluate the expression at all (the input handler is not called at all). After using `later::run_now()`, the expression is evaluated.

I've recreated it both running rstudio server through the [rocker-org/rstudio](https://github.com/rocker-org/rocker/wiki/Using-the-RStudio-image) docker container and
the [Bioconductor AMI](https://www.bioconductor.org/help/bioconductor-cloud-ami/#connecting_rstudio).

The example works as expected with R in the command line (after ssh into the container/instance).

Any ideas on how Rstudio server may be interfering with the R event loop?

PS. These docker/ami setups are used a lot for workshops and tutorials so it would be great make this work.

PS2. We have seen this (well, not using later, but for daemonized httpuv) work before on these rstudio server setups, as recently as last week, so this is a bit of a mystery.

**Comment by jcheng5** [comment]
cc @jmcphers

**Comment by jmcphers** [comment]
Can confirm this happens on RStudio Server reliably -- but works fine on RStudio Desktop! Curious, since we wrap the R session very similarly. This is where the interesting bits of our R event loop integration live:

https://github.com/rstudio/rstudio/blob/54cd3abcfc58837b433464c793fe9b03a87f0bb4/src/cpp/r/session/REmbeddedPosix.cpp

It may be the case that we need to nudge R to run its event loop in server mode (it looks like we invoke `processEvents` in the desktop, but not the server). I'll file a bug and we'll look into it further.

**Comment by kevinushey** [comment]
Indeed, adding a call to `R_ProcessEvents()` for RStudio Server resolves this issue, although I'm not yet sure if that's the actual solution we want to take here as I don't fully understand the implications of that change.

**Comment by jmcphers** [comment]
FYI @kevinushey just fixed this on RStudio master. @hcorrada, build 1.1.273 or higher will have the fix for you to verify; you can pick it up here after it's built:

https://dailies.rstudio.com/

**Comment by hcorrada** [comment]
Thank you! We'll test in the next couple of days and close this.
Thanks!
