### ISSUE TITLE
Compilation failed on linux (el7) during installation of Shiny Server

### ISSUE THREAD

**Issue by iron0012** [r-lib/later#62]
While attempting to install Shiny Server using this command from the instructions:
sudo su - \
-c "R -e \"install.packages('shiny', repos='https://cran.rstudio.com/')\""

The compilation of 'later' package fails. This seems to be the pertinent part of the output:

In file included from /usr/lib64/R/library/Rcpp/include/Rcpp.h:77:0,
                 from ../inst/include/later.h:6,
                 from RcppExports.cpp:4:
/usr/lib64/R/library/Rcpp/include/Rcpp/Rmath.h: In function ‘double R::pythag(double, double)’:
/usr/lib64/R/library/Rcpp/include/Rcpp/Rmath.h:222:55: error: ‘::Rf_pythag’ has not been declared
     inline double pythag(double a, double b) { return ::Rf_pythag(a, b); }
                                                       ^
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘later’

Since this is linux, I cannot install a binary version of the package (can I?), so I am stuck, and cannot install Shiny Server.

**Comment by iron0012** [comment]
Okay, this seems to be a problem with the version of 'later' on CRAN, but not the github version. So after doing this, I was able to install Shiny Server as recommended:

**Comment by wch** [comment]
That's very surprising, since the CRAN version (0.7.3) should be the same as what's on Github. The only difference is that CRAN has a source package, and Github has the raw sources (which can be built into a source package).

A couple questions:

Does installing from CRAN work now? You can run this command again:

```
sudo su - -c "R -e "install.packages('later', repos='https://cran.rstudio.com/')\""
```

If it does work, then it's possible that `remotes::install_github` updated some upstream dependency automatically for you.

Also, do you have old packages that are installed on your system? If you run the following in R, what output do you get?

```R
pkgs <- as.data.frame(installed.packages(), stringsAsFactors = FALSE, row.names = FALSE)
pkgs[, c("Package", "Version", "Built")]
```
The reason I ask this question is that, if you upgraded R but have old packages that were still around that were from a previous R version, this can cause problems. For more information about this, see https://shiny.rstudio.com/articles/upgrade-R.html.

**Comment by iron0012** [comment]
Hi, thank you for your response. Installing from CRAN does indeed work now, and you were correct that I had old packages still installed on my system. 

Thanks very much for your link; I wish I had found it earlier! I was able to upgrade all packages with update.packages(ask = FALSE, checkBuilt = TRUE)
