### ISSUE TITLE
Unable to compile on linux, "Mutex creation failed"

### ISSUE THREAD

**Issue by deluciaatgfz** [r-lib/later#63]
I can't compile later on my linux (Arch Linux), which breaks some dependencies for me. I get this error (both from github and CRAN): 

``
** testing if installed package can be loaded
sh: riga 1:  5012 Annullato               (core dump creato) '/usr/lib64/R/bin/R' --no-save --slave 2>&1 < '/tmp/Rtmp8kWDUc/file136713a0f686'
terminate called after throwing an instance of 'std::runtime_error'
  what():  Mutex creation failed
ERROR: loading failed
* removing ‘/usr/lib/R/library/later’
``
This is my sessioninfo:

`R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Arch Linux

Matrix products: default
BLAS: /usr/lib/libblas.so.3.8.0
LAPACK: /usr/lib/liblapack.so.3.8.0

locale:
 [1] LC_CTYPE=it_IT.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=it_IT.UTF-8        LC_COLLATE=it_IT.UTF-8    
 [5] LC_MONETARY=it_IT.UTF-8    LC_MESSAGES=it_IT.UTF-8   
 [7] LC_PAPER=it_IT.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=it_IT.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.1  R6_2.2.2        htmltools_0.3.6 tools_3.5.1    
[5] Rcpp_0.12.18    remotes_1.1.1   digest_0.6.15   fortunes_1.5-4 
`

**Comment by jpds** [comment]
Similiar to #45.

**Comment by deluciaatgfz** [comment]
Have you got any clue on what it's going on? 
On debian it compiles fine.

**Comment by wch** [comment]
This sounds like the same issue reported in rstudio/shiny#2150. It sounds like there may be an issue with the version of glibc that Arch uses.

Related: https://bugs.archlinux.org/task/59550

**Comment by jannes-m** [comment]
I have downgraded  `glibc` to version 2.27-3, however, the problem still persists. Any ideas @pat-s (`later` is a dependency of `xaringan`)?

**Comment by pat-s** [comment]
Seems like we have to wait for a `glibc` fix for now if downgrading also does not help here. 

This bug affects a lot in Arch right now including email clients, slack and more..

**Comment by ByteHamster** [comment]
Downgrading helped on my device

**Comment by pat-s** [comment]
@ByteHamster Any tips how you rolled back safely?

`sudo pacman -U /var/cache/pacman/pkg/lib32-glibc-2.28-1-x86_64.pkg.tar.xz /var/cache/pacman/pkg/glibc-2.27-3-x86_64.pkg.tar.xz` did not seem to do the job.

```
sudo pacman -Q --info glibc
Name            : glibc
Version         : 2.28-1
```

**Comment by ByteHamster** [comment]
I did `sudo pacman -U /var/cache/pacman/pkg/glibc-2.27-3-x86_64.pkg.tar.xz /var/cache/pacman/pkg/lib32-glibc-2.27-3-x86_64.pkg.tar.xz`

```
pacman -Q --info glibc
Name            : glibc
Version         : 2.27-3
```

**Comment by pat-s** [comment]
Thanks. Seems the order of the packages makes a difference. Works now!

**Comment by jannes-m** [comment]
Ok, the downgrade now also worked for me, thanks everybody!

**Comment by znmeb** [comment]
Yeah - I'm on Arch Linux and this is a mess ... a lot of R package installs break, not just `later`. And Skype. And Slack. And Electron apps. :-(

**Comment by wch** [comment]
We just merged a fix into master. For everyone who has experienced a problem, can you test and report back with how it works, and the platform you're on?

```R
devtools::install_github("r-lib/later")
```

**Comment by znmeb** [comment]
Works for me on Arch Linux - thanks!

**Comment by EngineerCoding** [comment]
Tested, works for me on arch linux (exact distro is Antergos) too. Thanks for the fix!

**Comment by jannes-m** [comment]
Same for me (Antergos Arch Linux), thank you very much!

**Comment by MaximeWack** [comment]
Works for me on Arch, thanks!

**Comment by alexisforestier** [comment]
tested and works for me on Manjaro, thank you very much!

**Comment by nacnudus** [comment]
Works for me on Arch, thanks!

**Comment by hermidalc** [comment]
Hi @wch and others - I'm stuck on this issue right now, multiple R packages do not install fully due to this error.

I try to install latest devtools::install_github("r-lib/later") to fix the problem but even trying to install it results in the same mutex creation failed error.  How did people get it installed?

**Comment by wch** [comment]
@hermidalc What platform are you using? Also, if you are familiar with Docker and are able to supply a Dockerfile that can reproduce the problem, that will be very helpful.

**Comment by hermidalc** [comment]
> @hermidalc What platform are you using? Also, if you are familiar with Docker and are able to supply a Dockerfile that can reproduce the problem, that will be very helpful.

I'm not very familiar with Docker.  My setup is straightfoward: Fedora 29 linux, Anaconda 5.2.0 with R 3.5.1.  Something somewhere has started to cause this error, maybe its not R later related but when I searched for this error only R later issues came up though mostly from back in August which made me think this is a new problem with R 3.5.1.

I swear I used to be able to compile even a couple weeks ago the R libraries with R 3.5.1 that now do not load and cannot be reinstalled (with mutex creation failed and coredump).  The reason I know this is because I had them already installed and now when I type library(later) for example you get the mutex creation failed error.  It's funny some libraries that need compilation do install and some don't and give this error.

I've done some troubleshooting and found that going back to R 3.4.3 all mutex creation failed and installation issues go away.  Both R 3.5.0 and 3.5.1 have this major problem.  I wouldn't be surprised if we start seeing more post of this issue soon.

**Comment by wch** [comment]
R 3.5.0 has been out since April. The version of later which has this fix has been on CRAN since 2018-09-18.

I think it's likely that it's either something specific to your system, or it's related to Fedora 29, which came out just a couple of weeks ago.

It also sounds like you may have R packages which you built with an older version of R. If that's the case, especially if they were built with R 3.4.x, then you should rebuild your packages with your current version of R. Please see this article for more information. http://shiny.rstudio.com/articles/upgrade-R.html

If you still have problems, please file a new issue with detailed system information and output from when you try to install the package.

**Comment by hermidalc** [comment]
@wch I think there was some misunderstanding as to what I wrote.

I never had R 3.4.3 installed, only ever R 3.5.1 and only ever built libs for this version. Only in my troubleshooting today did I try R 3.4.3 which was never there before.

I do agree it could be something with Fedora 29, but more specifically a recent Linux kernel update. Since I’m using Anaconda R and since Anaconda does not depend on anything from the system particularly compilers and system libs, then I’m hazarding a guess that it’s been one of the 4.18.1x recent Linux kernels that is causing the issue. Fedora 29 is on 4.18.18 now and I believe I still had the issue on 4.18.17 and maybe even before.

**Comment by wch** [comment]
@hermidalc Possibly relevant:

* ContinuumIO/anaconda-issues#10264
* https://github.com/AnacondaRecipes/aggregate/commit/c6db9437f66eed06f4dabd969736e10d8e30a977

**Comment by mingwandroid** [comment]
This bug is in glibc. https://sourceware.org/git/gitweb.cgi?p=glibc.git;a=commitdiff;h=e7feec374c635b6a29d65c39ae5e1855528fed39

**Comment by mingwandroid** [comment]
> Since I’m using Anaconda R and since Anaconda does not depend on anything from the system particularly compilers and system libs

Incorrect, Anaconda depends on your system glibc.

**Comment by wch** [comment]
@mingwandroid Is there anything we can/should do in the later package to deal with the bug?

**Comment by hermidalc** [comment]
@wch I’ve read many posts dealing with R and C11 threads issue, mostly from August, what I don’t understand is how people where able to rectify it by installing the latest patched version of later, which in my case I can’t do that due to the bug itself. How were they able to get it to install?

**Comment by wch** [comment]
I know very little about how Anaconda works, but perhaps you're installing the current version that Anaconda provides (0.7.3) instead of the latest version on CRAN (0.7.5).

As for how to install the latest CRAN version, in a normal R installation you would run `install.packages("later")`.

**Comment by mingwandroid** [comment]
@hermidalc, you are only having trouble with installing another R later because you are using R later in your workflow. There's no need to do that. Use a 'raw' R interpreter from a shell prompt to build the package instead.

**Comment by znmeb** [comment]
I have Fedora 29 (Silverblue) - I installed R and RStudio Desktop and the tidyverse a few weeks ago without incident. I can test this now. The versions of the packages may be slightly different from Fedora 29 Workstation but with Silverblue it's trivial to bring up a pure Fedora 29 container to test with.

@hermidalc How are you installing Anaconda?

**Comment by mingwandroid** [comment]
I see people saying other R libraries are affected by this, do they all use tinycthreads?

**Comment by mingwandroid** [comment]
@wch, I can confirm that the latest release is still broken in the same way:

```
** testing if installed package can be loaded
sh: line 1:   802 Aborted                 '/opt/conda/envs/r351rlater/lib/R/bin/R' --no-save --slave 2>&1 < '/tmp/RtmpAjkiS2/file2ab28994a62'
terminate called after throwing an instance of 'std::runtime_error'
  what():  Mutex creation failed
ERROR: loading failed
```

**Comment by znmeb** [comment]
When I ran into this in August, only `later` was actually failing. All the other failures were from packages failing because they depended on `later`.

**Comment by hermidalc** [comment]
@wch @znmeb thanks very much for the great support and troubleshooting

**Comment by mingwandroid** [comment]
@hermidalc, I identified the real problem here in https://github.com/r-lib/later/issues/63#issuecomment-439332484

I'd like to say it was a pleasure but that's be a lie.

**Comment by znmeb** [comment]
@hermidalc As a side note, I'm curious why you are installing R from Anaconda and not installing the data science stack packages (like `later`) from the Anaconda binaries. The few times I've loaded the whole Anaconda platform, I've just installed their versions of R, RStudio and the packages from their repository. I'd only install a package from CRAN or GitHub if it wasn't in their stack already.

**Comment by hermidalc** [comment]
> 
> 
> @hermidalc As a side note, I'm curious why you are installing R from Anaconda and not installing the data science stack packages (like `later`) from the Anaconda binaries. The few times I've loaded the whole Anaconda platform, I've just installed their versions of R, RStudio and the packages from their repository. I'd only install a package from CRAN or GitHub if it wasn't in their stack already.

It was just shown as an example of a library that cannot be compiled and installed from within R.  There are many others that do not exist as a package in any channel on conda and therefore must be installed from within R resulting in the same mutex creation failed and coredump.

**Comment by mingwandroid** [comment]
@hermidalc, it does build, it just fails to load. Also some of your technical problems around attempting to help out with this issue seem to stem from using rstudio (or some other complex software stack) which depends on later (I guess, but something in your stack certainly does) and trying to build later from within that env. That's not a good idea. Build r packages from a minimal environment. Use just a shell and the R executable when doing low level stuff like this. Minimalism should always be the rule when building software. And avoiding packages that are broken is obviously essential.

Ok that won't fix this later vs glibc 2.28 incompatibility (the maintainers of later will fix that and I'll continue to try to help if I have time) but I'd still try to follow this recommendation.

**Comment by hermidalc** [comment]
> @hermidalc, it does build, it just fails to load. Also some of your technical problems around attempting to help out with this issue seem to stem from using rstudio (or some other complex software stack) which depends on later (I guess, but something in your stack certainly does) and trying to build later from within that env. That's not a good idea. Build r packages from a minimal environment. Use just a shell and the R executable when doing low level stuff like this. Minimalism should always be the rule when building software. And avoiding packages that are broken is obviously essential.
> 
> Ok that won't fix this later vs glibc 2.28 incompatibility (the maintainers of later will fix that and I'll continue to try to help if I have time) but I'd still try to follow this recommendation.

@mingwandroid I'm not using rstudio.  I think you are confusing me with @twilbers who opened the other issue where we were discussing this problem https://github.com/ContinuumIO/anaconda-issues/issues/10264.  In that issue I mentioned that I was having this problem with Anaconda R itself so that it is likely not an rstudio issue.  Also as I mentioned in that issue, one reason I also posted there is because that was only person on the web mentioning this problem since August or so, so felt I should add to it saying its likely not rstudio.

**Comment by hermidalc** [comment]
> Build r packages from a minimal environment. Use just a shell and the R executable when doing low level stuff like this. Minimalism should always be the rule when building software. And avoiding packages that are broken is obviously essential.
> 
> Ok that won't fix this later vs glibc 2.28 incompatibility (the maintainers of later will fix that and I'll continue to try to help if I have time) but I'd still try to follow this recommendation.

I just went back to Anaconda R 3.4.3 for now as it has zero problems and my development environment is working again.  Once the R team fixes 3.5.1 I'll give it another try.

**Comment by mingwandroid** [comment]
> Once the R team fixes 3.5.1 I'll give it another try.

Do you mean once the later team fixes this bug here? If not, what is the issue with 3.5.1?

**Comment by mingwandroid** [comment]
This is not a bug with R, nor is it the recommended way to use Anaconda Distribution R packages.

conda install r-later

.. is the way to do that.

But until this bug gets fixed you need to use glibc < 2.18

**Comment by mingwandroid** [comment]
This is not and never was an Anaconda issue, except as a knock on from this upstream issue.

0.7.5 does not fix this. We know exactly how to fix it; by renaming these (now, since glibc 2.18) conflicting functions.

**Comment by hermidalc** [comment]
> 
> 
> This is not and never was an Anaconda issue, except as a knock on from this upstream issue.
> 
> 0.7.5 does not fix this. We know exactly how to fix it; by renaming these (now, since glibc 2.18) conflicting functions.

Ok, thank you for the clarification, I am fine with R 3.4.3 until things are ready
