### ISSUE TITLE
100% CPU in Console

### ISSUE THREAD

**Issue by alandipert** [r-lib/later#74]
A user noticed over at https://github.com/rstudio/websocket/issues/34 that websocket seems to use 100% when run from the R console.

This problem doesn't seem to manifest in RStudio. The following code run at the console will demonstrate the problem:

```
library(later)

testLater <- function() {
  later::later(testLater, 0.01)
}

testLater()
```
```
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] later_0.7.5

loaded via a namespace (and not attached):
[1] compiler_3.5.1 Rcpp_0.12.19   rlang_0.3.0.1
```

**Comment by jcheng5** [comment]
The problem is this piece of code in `later_posix.cpp`:

```cpp
  ~SuspendFDReadiness() {
    if (!idle()) {
      set_fd(true);
    }
  }
```

The presence of this code means that whenever a callback schedules another callback (or a future callback exists for any reason at all) then the fd will get and stay hot. This causes the input handler callback to be called repeatedly, as fast as R can do it. With R at the terminal, that's very very fast; with RStudio, for some reason the input handlers are called much less frequently just in general.

This may be the fix:

```cpp
  ~SuspendFDReadiness() {
    if (!idle()) {
      timer.set(*callbackRegistry.nextTimestamp());
    }
  }
```

Instead of leaving the fd hot, it sets a time in the future (or possibly past) for the fd to be activated.
